### ISSUE TITLE
Opening code in Sublime Text 2 did not work.

### ISSUE THREAD

**Issue by Arkkimaagi** [turbobabr/sketch-devtools-assistant#1]
I could not get the Open in Sublime Text feature to work from the DevTools. I'm using Sublime Text 2 and it was running when I tried. Nothing just happened.

Is there some way I can debug this?

**Comment by turbobabr** [comment]
I did test it with Sublime Text 3 only with the thought in mind that no one use 2nd version. :) But there is a workaround:
- You install [this guy](https://github.com/asuth/subl-handler)
- And setup a custom protocol handler like this:
  ![group](https://cloud.githubusercontent.com/assets/6356526/4770033/30a831f6-5b81-11e4-9b64-51b3726b06ea.png)

Template string: subl://open?url={file}&line={line}&column={column}

Let me know if it works for you.

**Comment by Arkkimaagi** [comment]
I was not able to get it working with subl-handler, but instead I got it running with https://github.com/dhoulb/subl and using this as the template:

```
subl://open?path=/Applications/Sublime%20Text%202.app&url={file}&line={line}&column={column}
```

So thank you!

PS. It might help others wondering if you'd use _Sublime Text 3_ instead of just _Sublime Text_ as the version 3 is still in beta. :)

**Comment by turbobabr** [comment]
Mikko,

I have just updated DevTools Assistant to solve this issue. Now if both versions of Sublime are installed Assistant prefers Sublime Text 2. Could you please check if it works?
- Quit Sketch DevTools Assistant App if it's running.
- Remove It from `Applications` folder.
- Download and install a new version [the same way](https://github.com/turbobabr/sketch-devtools-assistant) you did it before.
- Relaunch Sketch.
- Enable DevTools panel using `command-option-k`
- Go to settings panel and change `Jump To Code Editor` field back to `Sublime`

Now it should work with Sublime 2 if it's installed.

**Comment by Arkkimaagi** [comment]
Works like a dream with my Sublime Text 2. I'm closing this as it totally fixed the problem without anything extra needed from the user.

Thank you!
