### ISSUE TITLE
Cannot run Applescript

### ISSUE THREAD

**Issue by cihadturhan** [turbobabr/sketch-devtools-assistant#2]
Hi Andrey,

I'm trying to use this tool to run the script but I couldn't get it work. I copied the text you've posted into Applescript editor and changed the Plugin directory according to my plugin i.e `/playground/Version.sketchplugin` and checked if the file exists. Here is mine:

``` Applescript
tell application "Sketch DevTools Assistant"
    run script at path "~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/playground/Version.sketchplugin"
end tell
```

It gives me error like

```
Sketch DevTools Assistant got an error: "~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/playground/Version.sketchplugin" doesn’t understand the “run script at path” message.
```

I search a while but any of them resolved my problem. Is this script works for you as expected or there are some backslash, space etc problems?

Thanks

**Comment by turbobabr** [comment]
Are you running it using the latest version of the Assistant App? Also, could you please check the app dictionary from Apple ScriptEditor. Do you see the following picture?

![image](https://cloud.githubusercontent.com/assets/6356526/5262974/6d06e8d0-7a5e-11e4-997d-335b2298f3c8.png)

**Comment by cihadturhan** [comment]
Oh wonderful, it worked now. I thought it automatically scans /applications folder but it doesn't. After adding Sketch DevTools Assistant it worked fine.

Thanks Andrey
